wandb_version: 1

epochs:
  desc: null
  value: 35
classes:
  desc: null
  value: 28
batch_size:
  desc: null
  value: 20
batch_size_val_test:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 5.0e-05
patience:
  desc: null
  value: 10
heads:
  desc: null
  value: 6
depth:
  desc: null
  value: 3
fc_transformer:
  desc: null
  value: 340
dataset:
  desc: null
  value: ConText
architecture:
  desc: null
  value: Transformer
cnn:
  desc: null
  value: convnext_tiny
weights:
  desc: null
  value: DEFAULT
name_model:
  desc: null
  value: fasttext.pkl
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685013175.75203
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.8
      5: 0.15.3
      8:
      - 5
